import { fileURLToPath, URL } from 'node:url';
import { transformAssetUrls } from '@quasar/vite-plugin';
import vue from '@vitejs/plugin-vue';
import { QuasarResolver } from 'unplugin-vue-components/resolvers';
import Components from 'unplugin-vue-components/vite';
import { defineConfig } from 'vite';
import dts from 'vite-plugin-dts';

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    vue({
      template: { transformAssetUrls },
    }),
    Components({
      dts: true,
      resolvers: [QuasarResolver()],
    }),
    dts({
      insertTypesEntry: true,
      outDir: './dist/types',
    }),
  ],
  resolve: {
    alias: {
      '@': fileURLToPath(new URL('./src', import.meta.url)),
      '#': fileURLToPath(new URL('./types', import.meta.url)),
    },
  },
  css: {
    preprocessorOptions: {
      scss: {
        api: 'modern-compiler', // or 'modern'
      },
    },
  },
  build: {
    lib: {
      entry: fileURLToPath(new URL('./src/index.ts', import.meta.url)),
      name: '@herodotus-cloud/bpmn-designer',
      fileName: (format) => (format === 'es' ? `index.${format}.mjs` : `index.${format}.js`),
    },
    minify: 'terser',
    terserOptions: {
      // 生产环境下移除console
      compress: {
        drop_console: true,
        drop_debugger: true,
      },
      keep_classnames: true,
    },
    rollupOptions: {
      // 确保外部化处理那些你不想打包进库的依赖
      external: [
        'quasar',
        'sweetalert2',
        'ids',
        'didi',

        'bpmnlint',
        'bpmnlint/rules/conditional-flows',
        'bpmnlint/rules/end-event-required',
        'bpmnlint/rules/event-sub-process-typed-start-event',
        'bpmnlint/rules/fake-join',
        'bpmnlint/rules/label-required',
        'bpmnlint/rules/no-bpmndi',
        'bpmnlint/rules/no-complex-gateway',
        'bpmnlint/rules/no-disconnected',
        'bpmnlint/rules/no-duplicate-sequence-flows',
        'bpmnlint/rules/no-gateway-join-fork',
        'bpmnlint/rules/no-implicit-split',
        'bpmnlint/rules/no-inclusive-gateway',
        'bpmnlint/rules/single-blank-start-event',
        'bpmnlint/rules/single-event-definition',
        'bpmnlint/rules/start-event-required',
        'bpmnlint/rules/sub-process-blank-start-event',
        'bpmnlint/rules/superfluous-gateway',
        'bpmn-js',
        'bpmn-js/lib/Modeler',
        'bpmn-js/lib/Viewer',
        'bpmn-js/lib/features/modeling/Modeling',
        'bpmn-js/lib/features/modeling/BpmnFactory',
        'bpmn-js/lib/model/Types',
        'bpmn-js/lib/util/DiUtil',
        'bpmn-js/lib/util/DrilldownUtil',
        'bpmn-js/lib/util/ModelUtil',
        'bpmn-js-bpmnlint',
        'bpmn-js-connectors-extension',
        'bpmn-js-properties-panel',
        'bpmn-js-properties-panel/lib/PropertiesActivator',
        'bpmn-js-token-simulation',
        'bpmn-js-token-simulation/lib/features/toggle-mode/modeler/ToggleMode',
        'bpmn-moddle',
        'camunda-bpmn-moddle',
        'camunda-bpmn-moddle/resources/camunda',
        'diagram-js',
        'diagram-js/lib/command/CommandStack',
        'diagram-js/lib/core/Canvas',
        'diagram-js/lib/core/ElementRegistry',
        'diagram-js/lib/core/EventBus',
        'diagram-js/lib/features/align-elements/AlignElements',
        'diagram-js/lib/features/selection/Selection',
        'diagram-js/lib/i18n/translate',
        'diagram-js/lib/model',
        'diagram-js/lib/util/Collections',
        'diagram-js-grid',
        'diagram-js-minimap',
        'highlight.js',
        'highlight.js/lib/core',
        'highlight.js/lib/languages/xml',
        'highlight.js/lib/languages/json',
        'pinia',
        'vue',
        '@bpmn-io/element-template-chooser',
        '@bpmn-io/properties-panel',
        '@herodotus-cloud/core',
        '@herodotus-cloud/bpmn-apis',
        '@herodotus-cloud/components',
        '@herodotus-cloud/form-apis',
        '@highlightjs/vue-plugin',
      ],
      output: {
        exports: 'named',
        assetFileNames: `assets/[ext]/[name][extname]`,
        // 在 UMD 构建模式下为这些外部化的依赖提供一个全局变量
        globals: {
          quasar: 'quasar',
          sweetalert2: 'sweetalert2',
          ids: 'Ids',
          didi: 'didi',

          bpmnlint: 'Bpmnlint',
          'bpmnlint/rules/conditional-flows': 'BpmnlintRulesConditionalFlows',
          'bpmnlint/rules/end-event-required': 'BpmnlintRulesEndEventRequired',
          'bpmnlint/rules/event-sub-process-typed-start-event':
            'BpmnlintRulesEventSubProcessTypedStartEvent',
          'bpmnlint/rules/fake-join': 'BpmnlintRulesFakeJoin',
          'bpmnlint/rules/label-required': 'BpmnlintRulesLabelRequired',
          'bpmnlint/rules/no-bpmndi': 'BpmnlintRulesNoBpmndi',
          'bpmnlint/rules/no-complex-gateway': 'BpmnlintRulesNoComplexGateway',
          'bpmnlint/rules/no-disconnected': 'BpmnlintRulesNoDisconnected',
          'bpmnlint/rules/no-duplicate-sequence-flows': 'BpmnlintRulesNoDuplicateSequenceFlows',
          'bpmnlint/rules/no-gateway-join-fork': 'BpmnlintRulesNoGatewayJoinFork',
          'bpmnlint/rules/no-implicit-split': 'BpmnlintRulesNoImplicitSplit',
          'bpmnlint/rules/no-inclusive-gateway': 'BpmnlintRulesNoInclusiveGateway',
          'bpmnlint/rules/single-blank-start-event': 'BpmnlintRulesSingleBlankStartEvent',
          'bpmnlint/rules/single-event-definition': 'BpmnlintRulesSingleEventDefinition',
          'bpmnlint/rules/start-event-required': 'BpmnlintRulesStartEventRequired',
          'bpmnlint/rules/sub-process-blank-start-event': 'BpmnlintRulesSubProcessBlankStartEvent',
          'bpmnlint/rules/superfluous-gateway': 'BpmnlintRulesSuperfluousGateway',
          'bpmn-js': 'BpmnJs',
          'bpmn-js/lib/Modeler': 'BpmnJsLibModeler',
          'bpmn-js/lib/Viewer': 'BpmnJsLibViewer',
          'bpmn-js/lib/features/modeling/Modeling': 'BpmnJsLibFeaturesModelingModeling',
          'bpmn-js/lib/features/modeling/BpmnFactory': 'BpmnJsLibFeaturesModelingBpmnFactory',
          'bpmn-js/lib/model/Types': 'BpmnJsLibModelTypes',
          'bpmn-js/lib/util/DiUtil': 'BpmnJsLibUtilDiUtil',
          'bpmn-js/lib/util/DrilldownUtil': 'BpmnJsLibUtilDrilldownUtil',
          'bpmn-js/lib/util/ModelUtil': 'BpmnJsLibUtilModelUtil',
          'bpmn-js-bpmnlint': 'BpmnJsBpmnlint',
          'bpmn-js-connectors-extension': 'BpmnJsConnectorsExtension',
          'bpmn-js-properties-panel': 'BpmnJsPropertiesPanel',
          'bpmn-js-properties-panel/lib/PropertiesActivator':
            'BpmnJsPropertiesPanelLibPropertiesActivator',
          'bpmn-js-token-simulation': 'BpmnJsTokenSimulation',
          'bpmn-js-token-simulation/lib/features/toggle-mode/modeler/ToggleMode':
            'BpmnJsTokenSimulationLibFeaturesToggleModeModelerToggleMode',
          'bpmn-moddle': 'BpmnModdle',
          'camunda-bpmn-moddle': 'CamundaBpmnModdle',
          'camunda-bpmn-moddle/resources/camunda': 'CamundaBpmnModdleResourcesCamunda',
          'diagram-js': 'DiagramJs',
          'diagram-js/lib/command/CommandStack': 'DiagramJsLibCommandCommandStack',
          'diagram-js/lib/core/Canvas': 'DiagramJsLibCoreCanvas',
          'diagram-js/lib/core/ElementRegistry': 'DiagramJsLibCoreElementRegistry',
          'diagram-js/lib/core/EventBus': 'DiagramJsLibCoreEventBus',
          'diagram-js/lib/util/Collections': 'DiagramJsLibUtilCollections',
          'diagram-js/lib/features/align-elements/AlignElements':
            'DiagramJsLibFeaturesAlignElementsAlignElements',
          'diagram-js/lib/features/selection/Selection': 'DiagramJsLibFeaturesSelectionSelection',
          'diagram-js/lib/model': 'DiagramJsLibModel',
          'diagram-js/lib/i18n/translate': 'diagram-js/lib/i18n/translate',
          'diagram-js-grid': 'DiagramJsGrid',
          'diagram-js-minimap': 'DiagramJsMinimap',
          'highlight.js': 'HighlightJs',
          'highlight.js/lib/core': 'HighlightJsLibCore',
          'highlight.js/lib/languages/xml': 'HighlightJslibLanguagesXml',
          'highlight.js/lib/languages/json': 'HighlightJsLibLanguagesJson',
          pinia: 'pinia',
          vue: 'vue',
          '@bpmn-io/element-template-chooser': 'BpmnIoElementTemplateChooser',
          '@bpmn-io/properties-panel': 'BpmnIoPropertiesPanel',
          '@herodotus-cloud/core': 'HerodotusCore',
          '@herodotus-cloud/bpmn-apis': 'HerodotusBpmnApis',
          '@herodotus-cloud/components': 'HerodotusComponents',
          '@herodotus-cloud/form-apis': 'HerodotusFormApis',
          '@highlightjs/vue-plugin': 'HighlightjsVuePlugin',
        },
      },
    },
  },
});
