/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    403: typeof import('./../src/components/error/403.vue')['default']
    404: typeof import('./../src/components/error/404.vue')['default']
    500: typeof import('./../src/components/error/500.vue')['default']
    HActionButton: typeof import('./../src/components/library/Table/HActionButton.vue')['default']
    HActionDeleteButton: typeof import('./../src/components/library/Table/HActionDeleteButton.vue')['default']
    HActionEditButton: typeof import('./../src/components/library/Table/HActionEditButton.vue')['default']
    HAppBar: typeof import('./../src/components/layouts/header/HAppBar.vue')['default']
    HAppBreadcrumbs: typeof import('./../src/components/layouts/header/HAppBreadcrumbs.vue')['default']
    HAppContainer: typeof import('./../src/components/layouts/HAppContainer.vue')['default']
    HAppDefaultLayout: typeof import('./../src/components/layouts/HAppDefaultLayout.vue')['default']
    HAppLeftDrawer: typeof import('./../src/components/layouts/drawer/HAppLeftDrawer.vue')['default']
    HAppLogo: typeof import('./../src/components/library/Logo/HAppLogo.vue')['default']
    HAppMenu: typeof import('./../src/components/layouts/drawer/HAppMenu.vue')['default']
    HAppRightDrawer: typeof import('./../src/components/layouts/drawer/HAppRightDrawer.vue')['default']
    HAppSettingOptions: typeof import('./../src/components/layouts/drawer/HAppSettingOptions.vue')['default']
    HAppTabMenuItem: typeof import('./../src/components/layouts/HAppTabMenuItem.vue')['default']
    HAppTabView: typeof import('./../src/components/layouts/HAppTabView.vue')['default']
    HBehaviorCaptcha: typeof import('./../src/components/captcha/HBehaviorCaptcha.vue')['default']
    HBehaviorCaptchaBackground: typeof import('./../src/components/captcha/HBehaviorCaptchaBackground.vue')['default']
    HBehaviorCaptchaControl: typeof import('./../src/components/captcha/HBehaviorCaptchaControl.vue')['default']
    HBehaviorCaptchaFeedback: typeof import('./../src/components/captcha/HBehaviorCaptchaFeedback.vue')['default']
    HButton: typeof import('@herodotus/components')['HButton']
    HCenterLayoutContainer: typeof import('./../src/components/form/HCenterLayoutContainer.vue')['default']
    HDataTable: typeof import('./../src/components/library/Table/HDataTable.vue')['default']
    HDetailContainer: typeof import('./../src/components/form/HDetailContainer.vue')['default']
    HDictionarySelect: typeof import('./../src/components/library/Select/HDictionarySelect.vue')['default']
    HErrorLayout: typeof import('./../src/components/error/HErrorLayout.vue')['default']
    HGraphicCaptcha: typeof import('./../src/components/captcha/HGraphicCaptcha.vue')['default']
    HJigsawCaptcha: typeof import('./../src/components/captcha/HJigsawCaptcha.vue')['default']
    HSettingLabel: typeof import('@herodotus/components')['HSettingLabel']
    HSettingThemeOption: typeof import('./../src/components/layouts/drawer/HSettingThemeOption.vue')['default']
    HTextDivider: typeof import('./../src/components/library/Divider/HTextDivider.vue')['default']
    HWordClickCaptcha: typeof import('./../src/components/captcha/HWordClickCaptcha.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
