/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    403: typeof import('./../src/components/application/error/403.vue')['default']
    404: typeof import('./../src/components/application/error/404.vue')['default']
    500: typeof import('./../src/components/application/error/500.vue')['default']
    HAppContainer: typeof import('./../src/components/application/layout/HAppContainer.vue')['default']
    HAppLeftDrawer: typeof import('./../src/components/application/layout/HAppLeftDrawer.vue')['default']
    HAppRightDrawer: typeof import('./../src/components/application/layout/HAppRightDrawer.vue')['default']
    HAppToolbar: typeof import('./../src/components/application/layout/HAppToolbar.vue')['default']
    HelloWorld: typeof import('./../src/components/HelloWorld.vue')['default']
    HErrorLayout: typeof import('./../src/components/application/error/HErrorLayout.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
