/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    403: typeof import('./../src/components/error/403.vue')['default']
    404: typeof import('./../src/components/error/404.vue')['default']
    500: typeof import('./../src/components/error/500.vue')['default']
    AppDefaultLayout: typeof import('./../src/components/layouts/app/AppDefaultLayout.vue')['default']
    AppLeftDrawer: typeof import('./../src/components/layouts/app/AppLeftDrawer.vue')['default']
    AppMenu: typeof import('./../src/components/layouts/app/AppMenu.vue')['default']
    AppRightDrawer: typeof import('./../src/components/layouts/app/AppRightDrawer.vue')['default']
    AppTabMenuItem: typeof import('./../src/components/layouts/app/AppTabMenuItem.vue')['default']
    AppTabView: typeof import('./../src/components/layouts/app/AppTabView.vue')['default']
    HActionButton: typeof import('./../src/components/library/Table/HActionButton.vue')['default']
    HActionDeleteButton: typeof import('./../src/components/library/Table/HActionDeleteButton.vue')['default']
    HActionEditButton: typeof import('./../src/components/library/Table/HActionEditButton.vue')['default']
    HAppLogo: typeof import('./../src/components/library/Logo/HAppLogo.vue')['default']
    HAppSettingOptions: typeof import('@herodotus/components')['HAppSettingOptions']
    HAppTabMenuItem: typeof import('@herodotus/components')['HAppTabMenuItem']
    HBehaviorCaptcha: typeof import('./../src/components/captcha/HBehaviorCaptcha.vue')['default']
    HBehaviorCaptchaBackground: typeof import('./../src/components/captcha/HBehaviorCaptchaBackground.vue')['default']
    HBehaviorCaptchaControl: typeof import('./../src/components/captcha/HBehaviorCaptchaControl.vue')['default']
    HBehaviorCaptchaFeedback: typeof import('./../src/components/captcha/HBehaviorCaptchaFeedback.vue')['default']
    HButton: typeof import('@herodotus/components')['HButton']
    HCenterLayoutContainer: typeof import('./../src/components/form/HCenterLayoutContainer.vue')['default']
    HColumnReserved: typeof import('./../src/components/library/Table/HColumnReserved.vue')['default']
    HColumnStatus: typeof import('./../src/components/library/Table/HColumnStatus.vue')['default']
    HColumnSwagger: typeof import('./../src/components/library/Table/HColumnSwagger.vue')['default']
    HDataTable: typeof import('./../src/components/library/Table/HDataTable.vue')['default']
    HDetailContainer: typeof import('./../src/components/form/HDetailContainer.vue')['default']
    HDictionarySelect: typeof import('./../src/components/library/Select/HDictionarySelect.vue')['default']
    HErrorLayout: typeof import('./../src/components/error/HErrorLayout.vue')['default']
    HGraphicCaptcha: typeof import('./../src/components/captcha/HGraphicCaptcha.vue')['default']
    HJigsawCaptcha: typeof import('./../src/components/captcha/HJigsawCaptcha.vue')['default']
    HParticles: typeof import('@herodotus/components')['HParticles']
    HSettingLabel: typeof import('@herodotus/components')['HSettingLabel']
    HSignInBackground: typeof import('@herodotus/components')['HSignInBackground']
    HTextDivider: typeof import('./../src/components/library/Divider/HTextDivider.vue')['default']
    HWordClickCaptcha: typeof import('./../src/components/captcha/HWordClickCaptcha.vue')['default']
    LayoutBar: typeof import('./../src/components/layouts/commons/LayoutBar.vue')['default']
    LayoutBreadcrumbs: typeof import('./../src/components/layouts/commons/LayoutBreadcrumbs.vue')['default']
    LayoutContainer: typeof import('./../src/components/layouts/commons/LayoutContainer.vue')['default']
    ProfileDefaultLayout: typeof import('./../src/components/layouts/profile/ProfileDefaultLayout.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingOptions: typeof import('./../src/components/layouts/setting/SettingOptions.vue')['default']
    SettingThemeOption: typeof import('./../src/components/layouts/setting/SettingThemeOption.vue')['default']
  }
}
