/// <reference types="vite/client" />

declare interface Window {
  APPLICATION_ENVIRONMENT_VARIABLES_PROJECT: string;
  APPLICATION_ENVIRONMENT_VARIABLES_APPLICATION_NAME: string;
  APPLICATION_ENVIRONMENT_VARIABLES_API_URL: string;
  APPLICATION_ENVIRONMENT_VARIABLES_WS_URL: string;
  APPLICATION_ENVIRONMENT_VARIABLES_OAUTH2_CLIENT_ID: string;
  APPLICATION_ENVIRONMENT_VARIABLES_OAUTH2_CLIENT_SECRET: string;
  APPLICATION_ENVIRONMENT_VARIABLES_OAUTH2_REDIRECT_URI: string;
  APPLICATION_ENVIRONMENT_VARIABLES_USE_DISABLE_DEVTOOL: string;
}
