/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const useDialogPluginComponent: typeof import('quasar')['useDialogPluginComponent']
  const useFormChild: typeof import('quasar')['useFormChild']
  const useMeta: typeof import('quasar')['useMeta']
  const useQuasar: typeof import('quasar')['useQuasar']
}
